# Generated by Django 3.0.3 on 2020-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_auto_20200709_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='therapist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
