# Generated by Django 3.0.3 on 2020-07-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_auto_20200709_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
